namespace Necromancy.Server.Model
{
    public enum ItemEquipDisplayType
    {
        None = 0,
        Knuckle = 0,
        Trump = 1,
        Dagger = 1,
        Foil = 2,
        Rapier = 3,
        Sword1H = 4,
        Sword2H = 5,
        Katana1H = 6,
        Katana2H = 7,
        Axe1H = 8,
        Axe2H = 9,
        Spear = 10,
        Club1H = 11,
        Club2H = 12,
        Wand1H = 13,
        Wand2H = 14,
        Bow = 15,
        Crossbow = 16,
        Gun = 17,
        Instrument = 18,
        ShieldSmall = 19,
        ShieldMedium = 20,
        ShieldLarge = 21,
        Arrow = 22,
        Bolt = 23,
        Bullet = 24,
        Armor = 25,
        Protector = 25, //PROTCT
        Accessory = 26, //ACCRY
        Other = 27,
        Helmet = Armor,
        Hat = Armor,
        Hood = Armor,
        ArmorTops = Armor, //ARMOR
        ArmorBottoms = Armor, //GREAVES
        ClothesTops = Armor, //TOP
        ClothesBottoms = Armor,
        Coat = Armor,
        Gloves = Armor,
        Gauntlets = Armor,
        Braclet = Armor,
        Sabatons = Armor, //S.SHOE
        Shoes = Armor, // SHOES
        Cloak = Armor, //
        Ring = Accessory,
        Earring = Accessory,
        Necklace = Accessory, //NCKLCE
        Belt = Accessory,
        Drug = Other, //MEDICINE
        Skillchip = Other, //SKLCHP
        Bag = Accessory,
        Lostsoul = Other, //LSTSOL
        Event = Other,
        Forgestone = Other, //FG_STN
        TalkringMakekit = Other, //TOKRNG
        MasterTalkring = Accessory, //TOKRING
        Talkring = Accessory, //TOKRNG
        Forgeguardstone = Other, //FG_GRD
        Gem = Other, //GEM
        GemPiece = Other, //GEM
        GemSynthesis = Other, //GEM
        MapFragment = Other, //MAP PC
        Others = Other, //OTHER
        Avatar = Armor,
        Allcht = Accessory,
        Buff = Other,
        Leather = Armor, //L.SHOES
        Forgeticket = Other, //FG_TKT
        ForgeSpSupport = Other, //特殊鍛錬万能素材
        Material = Other, //JP ONLY
        Wholechat = Allcht
    }
}
